### ISSUE TITLE
Please add screenshot in ReadMe.md

### ISSUE THREAD

**Issue by zaisahil** [Labs64/laravel-boilerplate#1]
Hi

Can you please add screenshot in your README.md file?

I want to contribute on your repo but I can't get what this boilerplate consists of?

Also, please write some documentation on your repo and enable the Wiki for this. 

-Saeed

**Comment by r-brown** [comment]
Hi @zaisahil , thank you for your note.
We've reworked https://github.com/Labs64/laravel-boilerplate/blob/master/README.md page and tried to provide here as much as possible information, which should help you to start with this boilerplate.

We'd appreciate your valuable feedback.

Best, Ready
