### ISSUE TITLE
Add user membership plan feature

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#10]
Introduce user subscription plans management panel:
- Labs64 [NetLicensing](http://netlicensing.io) [subscription](https://www.labs64.de/confluence/x/ugCo) licensing model need to be used
  - configure demo product with following terms: _1 day, 1 week, 1 month, 1 year_
- show license expiration / validity in a table
- allow user to extend license => forward to the NetLicensing Shop
- use latest available release for [Labs64 NetLicensing PHP Client](https://github.com/Labs64/NetLicensingClient-php/releases)

**Comment by v-rudkovskiy** [comment]
[Added in Labs64/laravel-boilerplate@744ce37](https://github.com/Labs64/laravel-boilerplate/commit/744ce3776910ff308b9d39edeba6d376c67eb101)

**Comment by r-brown** [comment]
Add [NetLicensing](http://netlicensing.io) configuration (product, product module + license model, license templates) here.

**Comment by v-rudkovskiy** [comment]
NetLicensing configuration:
1) Sign up or Log in [Netlicensing](http://netlicensing.io/)
2) Create product in [Netlicensing Products](https://go.netlicensing.io/console/v2/content/vendor/product.xhtml). 
Attention!! Do not forget to activate "Auto-create Licensee"
3) Create product module in [Netlicensing Product Modules](https://go.netlicensing.io/console/v2/content/vendor/productmodule.xhtml). In the Product Number field, select the product you created earlier.
4) Create License Template in [Netlicensing License Templates](https://go.netlicensing.io/console/v2/content/vendor/licensetemplate.xhtml).In the Product Module Number field, select the product module you created earlier.

**Comment by r-brown** [comment]
@v-rudkovskiy - TODOs

- :white_check_mark: use` nlic` as short for all functions instead of `nl`
- :white_check_mark: do not use `netlicensing` as path
  - move `membership.blade.php` outside of `netlicensing` folder
  - move `permissions.blade.php` to the `admin` folder
  - merge `MembershipController.php` and `PermissionsController.php`
- :white_check_mark: use only one page for the membership area
  - merge `membership.blade.php` and `shop.blade.php` and render permissions based on the current user status
  - introduce a new macro `membership.data`, which can be used to change .blades layout; e.g. `membership.data.valid` returns users current status
  - possible fields at `membership.data` => _licensee number, valid, expiration, product module, license model, etc._
- :white_check_mark: use user's E-Mail as Licensee Number 
- :white_check_mark: use user's Name as Licensee Name
- :white_check_mark: allow the user to extend license, even is he has already valid subscription
- :white_check_mark: show expiration date to the user in the membership area
- :white_check_mark: configure demo product with following terms: _1 day, 1 week, 1 month, 1 year_
- :white_check_mark: NetLicensing _validate_ and _shop token create_ logic is duplicated in different classes
  - consider creating only one helper class and use it everywhere

@r-brown - TODOs
- :white_check_mark: create documentations page [Membership Plans setup](https://github.com/Labs64/laravel-boilerplate/wiki/Membership-Plans-setup)

**Comment by r-brown** [comment]
## NetLicensing - create product

<img width="576" alt="laravel-boilerplate-nlic-01-product" src="https://user-images.githubusercontent.com/1361258/27259270-fd09d640-540e-11e7-8990-5a18aaa5e923.png">

## NetLicensing - create product module

<img width="473" alt="laravel-boilerplate-nlic-02-productmodule" src="https://user-images.githubusercontent.com/1361258/27259269-fd0957e2-540e-11e7-86de-7d8f7941d42b.png">

## NetLicensing - create license template

<img width="495" alt="laravel-boilerplate-nlic-03-license-template" src="https://user-images.githubusercontent.com/1361258/27259268-fd094b94-540e-11e7-868e-6cb60fd5a918.png">

## NetLicensing - license templates list

<img width="996" alt="laravel-boilerplate-nlic-04-license-templates" src="https://user-images.githubusercontent.com/1361258/27260148-b511ace4-5424-11e7-9b3a-37cd708e79fb.png">

**Comment by v-rudkovskiy** [comment]
NetLicensing configuration:
1) Sign up or Log in [Netlicensing](http://netlicensing.io/)
2) Create product in [Netlicensing Products](https://go.netlicensing.io/console/v2/content/vendor/product.xhtml). 
Attention!! Do not forget to activate "Auto-create Licensee"
3) Create product module in [Netlicensing Product Modules](https://go.netlicensing.io/console/v2/content/vendor/productmodule.xhtml). In the Product Number field, select the product you created earlier.
4) Create License Template in [Netlicensing License Templates](https://go.netlicensing.io/console/v2/content/vendor/licensetemplate.xhtml).In the Product Module Number field, select the product module you created earlier.

**Comment by r-brown** [comment]
@v-rudkovskiy current status - Application broken => TO BE FIXED as soonest
- :white_check_mark: if a new users accesses Member Area - exception is thrown
  - admin user ; error _Unsupported response status code 400: Licensee with the number 'admin.laravel@labs64.com' does not exist._
  - demo user ; error : _Call to a member function getValidationResult() on null_
- :white_check_mark: purpose of the `dest` query params is not known
  http://localhost/membership/order-confirmation?dest=http%3A%2F%2Flocalhost%2Fmembership
- :white_check_mark: Management->Membership page doesn't work
  error: _View [netlicensing.permissions] not found._
- :white_check_mark: _cancel_url_title_ isn't set properly
- :white_check_mark: _cancel_url_ isn't set properly
- :white_check_mark: Table: nlic_shop_tokens defines too many indexes
  - consider to reduce to needed only
- :white_check_mark: Table: nlic_validations defines too many indexes
  - consider to reduce to needed only
- :white_check_mark: newly created user cannot be validated via admin.membership
  - SQL error is thrown
- :white_check_mark: test with fresh database and new users need to be executed (manually)

**Comment by v-rudkovskiy** [comment]
To protect the pages, use middleware `"protection: {product-module-number}, {failed-route-name}"`
where:
- `{product-module-number}` - the product module number created at NetLicensing
- `{failed-route-name}` - the name of the route to handle non-authorized access.

```php
// Example
Route::get('foo-path', 'FooController@index')->middleware('protection:foo-product-module-number, boo.path.access_denied');
Route::get('boo-path/access-denied','FooController@accessDenied')->name('boo.path.access_denied');
```

To protect content of the page, use blade directive `"protection"`.

```blade
// Example
@protection(foo-product-module-number-1)
    Access granted to foo-product-module-number-1
@elseifprotection(foo-product-module-number-2)
    Access granted to foo-product-module-number-2
@elseprotection
    Access denied
@endprotection
```

**Comment by r-brown** [comment]
Documentation updated: https://github.com/Labs64/laravel-boilerplate/wiki/Membership-Plans-setup#source-code-examples
