### ISSUE TITLE
Enable Invisible reCAPTCHA

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#11]
see more at https://laravel-news.com/invisible-recaptcha-integration-with-laravel

**Comment by v-rudkovskiy** [comment]
[Enabled in Labs64/laravel-boilerplate@d63e8cc](https://github.com/Labs64/laravel-boilerplate/commit/d63e8cc93bbde8db4f46e7f8b369bab442937569)

**Comment by r-brown** [comment]
Yet to be tested and documented

**Comment by r-brown** [comment]
Test - OK
Documentation - [In progress](https://github.com/Labs64/laravel-boilerplate/wiki/Invisible-reCAPTCHA-configuration)

**Comment by r-brown** [comment]
## Setup reCAPTCHA
Navigate to https://www.google.com/recaptcha/admin and set up a new reCAPTCHA

<img width="603" alt="laravel-boilerplate-recaptcha-01" src="https://user-images.githubusercontent.com/1361258/27258986-cae71d7c-5408-11e7-9d0f-124b7817af84.png">

## Adjust configuration properties

Open .env file and enter generated `Site key` and `Secret key` values
```
# reCAPTCHA
INVISIBLE_RECAPTCHA_SITEKEY=
INVISIBLE_RECAPTCHA_SECRETKEY=
INVISIBLE_RECAPTCHA_BADGEHIDE=false
INVISIBLE_RECAPTCHA_DEBUG=false

```
<img width="956" alt="laravel-boilerplate-recaptcha-02" src="https://user-images.githubusercontent.com/1361258/27258988-cb0786f2-5408-11e7-948b-28b929601ae4.png">

## reCAPTCHA rendering on the registration screen

<img width="601" alt="laravel-boilerplate-recaptcha-03" src="https://user-images.githubusercontent.com/1361258/27258987-cb06fcbe-5408-11e7-90ca-0950374a4bdf.png">

**Comment by r-brown** [comment]
Documentation created at [Invisible reCAPTCHA configuration](https://github.com/Labs64/laravel-boilerplate/wiki/Invisible-reCAPTCHA-configuration)

**Comment by r-brown** [comment]
Good job Albert ( @albertcht ). We'd appreciate if could reference [Laravel Boilerplate](https://github.com/Labs64/laravel-boilerplate) project as a showcase for the _Invisible reCAPTCHA_.

**Comment by albertcht** [comment]
Sure, why not? :)
