### ISSUE TITLE
Erro ao enviar link de Ativação!

### ISSUE THREAD

**Issue by Eduardoavargas** [Labs64/laravel-boilerplate#12]
Ao enviar link de ativação por email, não esta gravando no bd o novo link gerado.
Esta faltando salvar.

> ConfirmController

.....

public function sendEmail(User $user)
    {

        $user->confirmation_code = Uuid::uuid4();
       

> Acrecentar isso ao codigo.

**$user->save();**

``

....

**Comment by r-brown** [comment]
> When sending activation link by email, it is not recording in the bd the new link generated.
> It's missing saving.

`$user->save();`

**Comment by v-rudkovskiy** [comment]
[Fixed in Labs64/laravel-boilerplate@a5030c3](https://github.com/Labs64/laravel-boilerplate/commit/a5030c36906b1b91d88352fa21d6aca524ae5298)
