### ISSUE TITLE
Upgrade Laravel to v5.5

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#13]
Laravel [5.5](https://laravel-news.com/category/laravel-5.5) is scheduled to be released in August of 2017 and will be the next major release.

Consider upgrading Laravel version to the latest 5.5

**Comment by r-brown** [comment]
Laravel 5.5 will require [PHP 7.0+](https://laravel-news.com/laravel-5-5-php-7-0)

**Comment by shirshak55** [comment]
It is released

**Comment by r-brown** [comment]
Thank you @bloggervista  - we'll address this change as soonest.

**Comment by shirshak55** [comment]
@r-brown can we send pull request to new feature?

**Comment by v-rudkovskiy** [comment]
Done in [Labs64/laravel-boilerplate@d2bbb68](https://github.com/Labs64/laravel-boilerplate/commit/d2bbb6813a5365775ef3c94a653503f59beab10d)

**Comment by r-brown** [comment]
CI Build failed after this commit: https://travis-ci.org/Labs64/laravel-boilerplate

**Comment by shirshak55** [comment]
@r-brown Can we make backend 100% React Js one? As react is mit and can be used safely

**Comment by shirshak55** [comment]
@r-brown you can check out core-ui which is bootstrap one. And bootstrap stable is ready to come and core-ui is already bootstrap 4 compatible. Let ditch these bootstrap 3 themes in backend .  People are tired of using bootstrap 4 on frontend and bootstrap 3. Making everything messy.

**Comment by v-rudkovskiy** [comment]
I'm sorry I forgot that version 5.5 only supports PHP 7

Fix in [Labs64/laravel-boilerplate@202f242](https://github.com/Labs64/laravel-boilerplate/commit/202f242212848102ddeb70cc3eac4d5c0d170bdf)

**Comment by shirshak55** [comment]
I guess we need to do more than changing composer.json file.

**Comment by v-rudkovskiy** [comment]
@bloggervista Everything is done according to instructions [Laravel Upgrading To 5.5.0 From 5.4](https://laravel.com/docs/5.5/upgrade)

**Comment by HermanMonteiro** [comment]
Hello friends, is this issue over? Do you need help with something?

**Comment by shirshak55** [comment]
yeah. i guess its over. But if you like there are plenty of such good package :)

**Comment by r-brown** [comment]
We consider Laravel 5.5 upgrade as finalized.

@bloggervista resp. your suggestion to enable reactJS support I'd say that this change is not in the scope of maintaining standard Laravel boilerplate with the standard templating approach.
I'd suggest inclusion of additional frameworks as Laravel Boilerplate fork.
