### ISSUE TITLE
How to use the gentelella element and how implemet implement?

### ISSUE THREAD

**Issue by Pattern88** [Labs64/laravel-boilerplate#16]
Hi,

I would to understand how i can use the gentelella html / css / js element?
And also how to implement angularjs and use it wit this boilerplate. Thank you :)

**Comment by r-brown** [comment]
Hi @Pattern88 

Thank you for your interest on [Laravel-Boilerplate](https://github.com/Labs64/laravel-boilerplate/)!

Currently, we do not use Angular in Laravel-Boilerplate; let me try to explain the approach however.

1. You need to download Angular by using this command:
```
$ npm install angular –save
```
`package.json` will get an additional angular dependency

2. Add path to the angular files at `webpack.mix.js` and execute following command:
```
$ npm run dev
```
Please refer to this resource https://laravel.com/docs/5.4/mix, which is explaining how to add _scripts_ and _css_ files using `mix`.

3. As last step you need to use Angular in blade templates. This can be achieved using `mix `function, e.g.
```
{{ Html::script(mix(--PATH_TO_ANGULAR--)) }}
```

**Comment by r-brown** [comment]
Please note:
Since Blade Templates and Angular2 Templates are having similar syntax, e.g. `{{ ... }}`, you need to use `@` character for all Angular variables. This way Blade Templates will simply ignore such commands.

**Comment by r-brown** [comment]
To be able to use your custom JavaScript and CSS files, you need to proceed with the similar approach as described above.
1.	Create new JS or CSS files at `resources/assets`
2.	Use `webpack.mix.js` to package resource files; these packed files will be finally stored at public.
Commands:
```
js - > mix.scripts
css - > mix.styles
```
… see more at https://laravel.com/docs/5.4/mix
3.	Use new resource files in templates:
a.	Either using HTML tags `script `or `link`
b.	Or helper class `Html `and function `mix`
```
for js {{ Html::script(mix(--PATH_TO_JS--)) }}
for css {{ Html::style(mix(--PATH_TO_CSS--)) }}
```
