### ISSUE TITLE
Use APIKey authentication for NetLicensing calls

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#17]
Enable [API Key](https://www.labs64.de/confluence/display/NLICPUB/Security) as an additional and default mode to communicate with [NetLicensing](http://netlicensing.io).
`LABS64_NETLICENSING_SECURITY_MODE=API_KEY`

**Comment by v-rudkovskiy** [comment]
Enabled the API Key as default mode  in [Labs64/laravel-boilerplate@0faad45](https://github.com/Labs64/laravel-boilerplate/commit/0faad459c274008867600a2ab38edf811174805f)
