### ISSUE TITLE
Add dashboard page to the boilerplate

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#18]
First three rows from demo dashboard https://colorlib.com/polygon/gentelella/index.html need to be added to [Laravel Boilerplate](https://github.com/Labs64/laravel-boilerplate/).
Dashboard should be a default page shown at admin area opening.

**Comment by r-brown** [comment]
- _Total registered users_ need to be shown in a first widget.
- Verify possibility to show [licensee ](https://www.labs64.de/confluence/x/sQCo)expiration related data on the dashboard as well
![laravel-boilerplate-dashboard](https://user-images.githubusercontent.com/1361258/28259420-702348e0-6ad6-11e7-80d5-b36a7502f7e1.png)

**Comment by v-rudkovskiy** [comment]
Add dashboard page - done
![laravel-boilerplate-dashboard](https://user-images.githubusercontent.com/3775910/29062280-bc677c08-7c29-11e7-9466-ccb338740077.png)

**Comment by r-brown** [comment]
No dashboard commits found and following error appears
```
(2/2) ErrorException
Unable to locate Mix file: /assets/admin/js/dashboard.js. Please check your webpack.mix.js output paths and try again. (View: /var/www/laravel-boilerplate/resources/views/admin/dashboard.blade.php)
```
