### ISSUE TITLE
Problem with meta helper

### ISSUE THREAD

**Issue by XristMisyris** [Labs64/laravel-boilerplate#22]
Hello guys, I am trying to use the meta helper but i cant find how ..

i am using on my controller `meta()->tag('description', ' test description');` but its not working....

p.s I have the blade directive @meta on my blade file

Thanks!

**Comment by v-rudkovskiy** [comment]
Hi, @XristMisyris 
This is due to the fact that Laravel caches views. To see the changes in the template, clear the cache with the command:
`php artisan view:clear` 
or manually delete cache files on the path storage/framework/views

**Comment by v-rudkovskiy** [comment]
Also I added in [Labs64/laravel-boilerplate@6033ba5](https://github.com/Labs64/laravel-boilerplate/commit/6033ba5b8d3bad9a844ff8bc9f1b7ce36c2d1e7f) Automatic meta update in blade templates, now you can use dynamic meta. But you still need to reset the views cache once after the update, after that the cache will not have to be reset anymore, the meta itself will be updated.

**Comment by XristMisyris** [comment]
@v-rudkovskiy Thank you very much! its working now.
