### ISSUE TITLE
Why am I unable to use 'require' in the javascript of this laravel build?

### ISSUE THREAD

**Issue by localteampartners** [Labs64/laravel-boilerplate#23]
I noticed this laravel boilerplate differs from the basic laravel install with missing bootstrap.js  and app.js files. I tried adding these files but was unable to use 'require.'  How can I activate the 'require' capabilities of the normal laravel. Thank You

**Comment by r-brown** [comment]
This project using WebPack to retrieve all JS dependencies; as Gentelella Admin Theme is Bootstrap based, we cannot omit mentioned resources and adding them here: https://github.com/Labs64/laravel-boilerplate/blob/master/webpack.mix.js#L80

btw. you can use the similar approach if you want to add other JS / CSS libraries.

----

see also this reply _How to use the gentelella element and how implemet implement?_ #16
