### ISSUE TITLE
Upgrade Gentelella to the latest version

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#24]
Currently [v1.3.0](https://github.com/Labs64/laravel-boilerplate/blob/master/package.json#L19) is used and can be updated to the [latest](https://github.com/puikinsh/gentelella/releases/tag/1.4.0)

**Comment by v-rudkovskiy** [comment]
The Labs64/laravel-boilerplate already uses Gentelella  version 1.3.0
![screenshot_6](https://user-images.githubusercontent.com/3775910/29127964-32bff19e-7d2b-11e7-8449-136f99362cef.png)

**Comment by r-brown** [comment]
Last released version of Gentelella is [1.4.0](https://github.com/puikinsh/gentelella/releases/tag/1.4.0)

**Comment by v-rudkovskiy** [comment]
We use npm, i will wait until they update the version there

**Comment by v-rudkovskiy** [comment]
In npm repo latest version 1.3.0

see also https://github.com/puikinsh/gentelella/issues/524

**Comment by spyworldxp** [comment]
version 1.3.0 doesn't support datatables.js

**Comment by v-rudkovskiy** [comment]
Asked the developers in [puikinsh/gentelella issue #586](https://github.com/puikinsh/gentelella/issues/586) whether they will be able to update the version in npm

**Comment by r-brown** [comment]
Blocking issue https://github.com/puikinsh/gentelella/issues/524 s resolved now and Gentelella _1.4.0_ is available at npmJS - https://www.npmjs.com/package/gentelella

**Comment by v-rudkovskiy** [comment]
Done in [Labs64/laravel-boilerplate@6351da1](https://github.com/Labs64/laravel-boilerplate/commit/6351da177b36f0eb6493c2eaf7c9def94b3f3387)
