### ISSUE TITLE
Extend dashboard by gallery

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#25]
Add photos carousel to the dashboard. Photos can be coming from [Photolancer Zone](https://photolancer.zone/) and show top 10 best photos.

**Comment by v-rudkovskiy** [comment]
![screenshot_2](https://user-images.githubusercontent.com/3775910/31338719-130a7c58-ad09-11e7-8e57-6eff781da439.png)

Done in [Labs64/laravel-boilerplate@631514e](https://github.com/Labs64/laravel-boilerplate/commit/631514eb8fd8039df9198b6d671ce440fc6d739f)

PS. need update photolancer.zone with commit c5be53b, in commit c5be53b I prepared the possibility of cross browser requests

**Comment by r-brown** [comment]
- images should be clickable and open [Photolancer Zone](https://photolancer.zone/photos) photo in a new window
- Change title to _'Popular [Photolancer Zone](https://photolancer.zone/photos) photos'_
- place carousel section after Registration Stats as last section

**Comment by v-rudkovskiy** [comment]
- images should be clickable and open [Photolancer Zone](https://photolancer.zone/photos) photo in a new window
- Change title to _'Popular [Photolancer Zone](https://photolancer.zone/photos) photos'_
- place carousel section after Registration Stats as last section

@r-brown Done in [Labs64/laravel-boilerplate@6db840a](https://github.com/Labs64/laravel-boilerplate/commit/6db840afa922ef8ea0c692397df53899528a1cd1)

**Comment by r-brown** [comment]
- use pretty-printed URL to the photo
e.g.
instead of
https://photolancer.zone/photos/81he87g1/detail
