### ISSUE TITLE
Remember Me functionality

### ISSUE THREAD

**Issue by vikramnirala** [Labs64/laravel-boilerplate#26]
Hi, thanks for this nice boilerplate for laravel projects.
I am trying to use remember me functionality of laravel, but I can't find any place where is user is attempting to authenticate. I need to use Auth::attempt or viaRemember, but I didn't found it in your repo. Could you please help me about it?? It's a bit urgent.

**Comment by v-rudkovskiy** [comment]
Hi @vikramnirala , the authorization logic after login form submit is described in trait AuthenticatesUsers.php 
![screenshot_1](https://user-images.githubusercontent.com/3775910/29563771-b709a528-8747-11e7-8e94-452d45d6f5d6.png)

I hope I understood your question correctly.
