### ISSUE TITLE
Vue.js frontend

### ISSUE THREAD

**Issue by cleciobarbosa** [Labs64/laravel-boilerplate#28]
It would be nice if the frontend was migrated to vue.js

**Comment by kajes** [comment]
Mind if I take a look at this?

**Comment by r-brown** [comment]
Hello @kajes,
Thank you for your support and - yes - we'll be happy to get your contribution.
If possible, we'd appreciate Vue.js integration to be made as an option to use boilerplate with, so users can decide whether they want to use Blade, Vue.js or even AngularJS version later on.
Best way to achieve this would be creation of a second dashboard for Vue.js.

We'll be waiting for your Push Request. Thank you!

**Comment by kajes** [comment]
Yeah, I was kind of thinking the same when looking at the code. I will probably need to construct some more endpoints to be able to load data into Vue templates. I'm thinking it may be good to use the api middleware for the new end points, but could use some opinions on that. An alternative would be to use the existing end points and simply do a check on the request headers to determine if a blade view should be loaded or if it's just supposed to return the views data as JSON.

Also, should the switch between Blade/Vue be made in the dashboard?

**Comment by r-brown** [comment]
Let's go for dedicated Vue endpoints, as this offers cleaner separation (even using namespace). Changing Blade/Vue based on the header might be hidden for the user and difficult to follow-up on.

You can even create a second menu item ( _Dashboard (Vue)_ ) in the left nav menu.
