### ISSUE TITLE
Handle invalid NetLicensing credentials

### ISSUE THREAD

**Issue by r-brown** [Labs64/laravel-boilerplate#29]
If [NetLicensing](https://netlicensing.io) connection attributes defined in `.env` are not valid - standard Laravel error page appears, which is not giving more details on the issue.

```
LABS64_NETLICENSING_USERNAME=...
LABS64_NETLICENSING_PASSWORD=...
LABS64_NETLICENSING_APIKEY=...
```

<img width="1100" alt="lb-401" src="https://user-images.githubusercontent.com/1361258/31806138-3be5fb10-b566-11e7-87e4-89dd794f114f.png">

NetLiecnsing communication error needs to be handled and a custom page should be shown to the user with detailed instructions, how to fix this issue.

**Comment by r-brown** [comment]
Wiki Troubleshooting page created and can be referenced from the error screen in Laravel Boilerplate: https://github.com/Labs64/laravel-boilerplate/wiki/NetLicensing-connection-error

**Comment by r-brown** [comment]
How to get NetLicensing API Key
![nlic-get-apikey](https://user-images.githubusercontent.com/1361258/31813601-49cca032-b587-11e7-8f5f-98b0a93e0f31.png)

**Comment by v-rudkovskiy** [comment]
Done in [Labs64/laravel-boilerplate@981d2b1](https://github.com/Labs64/laravel-boilerplate/commit/981d2b1655ce528fa7a5be4140de3e3c761e58de)
![screenshot_1](https://user-images.githubusercontent.com/3775910/31877398-028cfaa0-b7df-11e7-8e07-fb83862e4886.png)

**Comment by v-rudkovskiy** [comment]
@r-brown  Please review issue
![screenshot_7](https://user-images.githubusercontent.com/3775910/31997830-0e74cb3c-b996-11e7-9ce1-64a0fb6a42f9.png)
![screenshot_8](https://user-images.githubusercontent.com/3775910/31997831-0e946f0a-b996-11e7-8ee3-ad2d4a15106c.png)

**Comment by r-brown** [comment]
@v-rudkovskiy please provide all possible error texts related to the [NetLicensing](https://netlicensing.io/) connectivity issue.
These texts will be used at https://github.com/Labs64/laravel-boilerplate/wiki/NetLicensing-Connection-Error and indexed by Google, so hit Google search icon will deliver hits.

**Comment by v-rudkovskiy** [comment]
Error texts related to the NetLicensing connectivity issue:
1) Missing parameter "username"
2) Missing parameter "password"
3) Missing parameter "apiKey"
4) Unknown security mode
5) Unsupported response status code 401: Unauthorized
