### ISSUE TITLE
Database Seeding Failure

### ISSUE THREAD

**Issue by webstractions** [Labs64/laravel-boilerplate#3]
Got almost all the way through the installation process, until database base migration and seeding. The migration worked fine, but seeding (`UsersSeeder`) produced an error:

` [Ramsey\Uuid\Exception\UnsatisfiedDependencyException]
  When calling Ramsey\Uuid\Converter\Time\DegradedTimeConverter::calculateTime on a 32-bit system, Moontoast\Math\BigNumber must be present.`

What is strange is that I am on a 64-bit system. So not sure what is going on here.

**Comment by webstractions** [comment]
I went ahead and commented out the two occurrences for `confirmation_code` in the UsersSeeder.php file and reran the migration with seeding. This works for now.

**Comment by v-rudkovskiy** [comment]
Fixed in [Labs64/laravel-boilerplate@1468e89](https://github.com/Labs64/laravel-boilerplate/commit/1468e8948d249749e1a97e709f66dd2fccd0eb4f)
