### ISSUE TITLE
jQuery.Deferred exception: Date.today is not a function

### ISSUE THREAD

**Issue by navarro8leo** [Labs64/laravel-boilerplate#30]
After cloned the repo, install and run. The following error appears in the browser's console: **jQuery.Deferred exception: Date.today is not a function TypeError: Date.today is not a function**

And is refered to this instruction, in the function: **init_flot_chart**, from the file: **/public/assets/admin/js**

![captura](https://user-images.githubusercontent.com/13022481/31854495-50ec00d8-b668-11e7-91e3-ed15e9771c0c.PNG)

The error don't appear always, just in some views. But when appears, the elements of the view don't respond correctly.

Have you any idea about what is the cause or how fix it?

Thanks in advance! :)

**Comment by v-rudkovskiy** [comment]
I see that a static method "today" has been created in the class Date in flot/date.js
Date.today=function(){return Date.now().clearTime();}

 flot/date.js connects through webpack.mix.js
![screenshot_5](https://user-images.githubusercontent.com/3775910/31880967-c4906410-b7ea-11e7-8297-adc69075111e.png)

@blue8leo Which browser do you have this error with and did you execute the command "npm run dev" or "npm run prod" after npm install?

**Comment by navarro8leo** [comment]
Hi,
I was trying with Chrome, and executed "npm run dev".

**Comment by v-rudkovskiy** [comment]
@blue8leo Fixed in [Labs64/laravel-boilerplate@c77783f](https://github.com/Labs64/laravel-boilerplate/commit/c77783fe57cfc9bfeb4fa393e4887534a309f6bd)

**Comment by navarro8leo** [comment]
Thanks, it works!
