### ISSUE TITLE
The Mix manifest does not exist

### ISSUE THREAD

**Issue by shaun-repairpilot** [Labs64/laravel-boilerplate#31]
Hi,

I have set the project up, and get the home page fine, but when I load any internal pages (member area, sign up or log in) I get the following error:

ErrorException (E_ERROR)
The Mix manifest does not exist. (View: /home/namehere/public_html/project/resources/views/auth/login.blade.php)

Any ideas on this?

Many thanks,

**Comment by shaun-repairpilot** [comment]
Any ideas?

**Comment by v-rudkovskiy** [comment]
@shaunbsoft Please exec command "npm run dev" or "npm run prod". After these commands, a public/mix-manifest.json file will be created

**Comment by shaun-repairpilot** [comment]
Tried running those, but get the error list below:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'prod' ]
2 info using npm@3.10.10
3 info using node@v6.11.5
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle @~preprod: @
6 silly lifecycle @~preprod: no script for preprod, continuing
7 info lifecycle @~prod: @
8 verbose lifecycle @~prod: unsafe-perm in lifecycle true
9 verbose lifecycle @~prod: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/bsoftwarecrm/public_html/dev.bsoftwarecrm/node_modules/.bin:/home/bsoftwarecrm/perl5/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/cpanel/composer/bin:/home/bsoftwarecrm/bin
10 verbose lifecycle @~prod: CWD: /home/bsoftwarecrm/public_html/dev.bsoftwarecrm
11 silly lifecycle @~prod: Args: [ '-c', 'npm run production' ]
12 silly lifecycle @~prod: Returned: code: 1  signal: null
13 info lifecycle @~prod: Failed to exec prod script
14 verbose stack Error: @ prod: `npm run production`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid @
16 verbose cwd /home/bsoftwarecrm/public_html/dev.bsoftwarecrm
17 error Linux 2.6.32-696.3.2.el6.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "prod"
19 error node v6.11.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @ prod: `npm run production`
22 error Exit status 1
23 error Failed at the @ prod script 'npm run production'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run production
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by v-rudkovskiy** [comment]
@shaunbsoft 
- Try running the command "npm install" before "npm run prod" command.
- Try to update node.js

**Comment by filippodicostanzo** [comment]
I have the same issue but only in shared hosting!

With vagrant works fine.

Any solution?

**Comment by r-brown** [comment]
Hi @shaunbsoft / @filippodicostanzo ,

Are you installing boilerplate using these installation steps: https://github.com/Labs64/laravel-boilerplate#installation ?
Could you please provide the details to your environment: PHP, Node.js, Composer, Operating System, other relevant info.

Best, r-brown

**Comment by filippodicostanzo** [comment]
Hi @r-brown,
I resolve with change the url of mix-manifest.json in my config file.

I move this file because I uploaded all files in shared domains.

Thank You!

**Comment by tomek-i** [comment]
Using vagrant on a windows machine with homestead it's causes the same issues, symlinks fail (acorns) and then tryng to run npm run dev  etc. ends up in an error: 

`sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! spawn ENOENT`
