### ISSUE TITLE
Installation instructions on Homestead

### ISSUE THREAD

**Issue by opulido** [Labs64/laravel-boilerplate#32]
Hi there. This boilerplate is packaged to work on docker. Could you add installation instructions to install it on [Homestead](https://laravel.com/docs/5.5/homestead)? Regards,

**Comment by opulido** [comment]
Hi guys. Is there a time frame for this enhancement? Regards!

**Comment by r-brown** [comment]
Hi @opulido , sorry for the delaying this enhancement. We had limited capacities available for this task around the new year.
We'll try to address this issues as soon as we'll be able to manage that.

Any idea, how you could possibly contribute to the same?
