### ISSUE TITLE
each() function in php5 ,7,7.1

### ISSUE THREAD

**Issue by rupadhyay-hd** [Labs64/laravel-boilerplate#33]
each() function in php5 ,7,7.1

when i run this project in this version not working give each() function error after click on user list

**Comment by r-brown** [comment]
Hello @rupadhyay-hd, we do not use PHP each() function.
Possibly this error is comming out of jQuery library:
https://github.com/Labs64/laravel-boilerplate/blob/c77783fe57cfc9bfeb4fa393e4887534a309f6bd/resources/assets/admin/js/dashboard.js#L110

May I ask you to:
- make sure, that all [Installations ](https://github.com/Labs64/laravel-boilerplate#installation)steps have been executed w/o errors
- provide error message for our reference

Best, R.Brown

**Comment by rupadhyay-hd** [comment]
Hello @r-brown 
Yes I follow all instruction but give this error in php each() 
Please check path "laravel-boilerplate/vendor/kyslik/column-sortable/src/ColumnSortable/Sortable.php"
Function "formatToSortParameters"   **$each = each($sort);**

**Comment by v-rudkovskiy** [comment]
@rupadhyay-hd 
What kind of error you catch? 
Most likely you have  problem with your php, because [each()](http://php.net/manual/en/function.each.php) function is standart php function.

**Comment by rupadhyay-hd** [comment]
Hello @r-brown 
Please check link if I am not wrong OR I use ubuntu with multiple php version that create issue 
http://php.net/manual/en/function.each.php

**Comment by r-brown** [comment]
Hi @rupadhyay-hd is it possible to verify this behavior with one PHP version only (ideally 7)

**Comment by r-brown** [comment]
Also exact error message would be really helpful.

**Comment by v-rudkovskiy** [comment]
laravel-boilerplate only support the version of PHP >=7.0
![screenshot_8](https://user-images.githubusercontent.com/3775910/32839797-a245903a-ca26-11e7-8253-ccdc47242383.png)

**Comment by r-brown** [comment]
Hi @rupadhyay-hd did you got a chance to test this issue with PHP > 7 version already?
