### ISSUE TITLE
Jquery was not initialized

### ISSUE THREAD

**Issue by raulti** [Labs64/laravel-boilerplate#37]
I'm brazilian
I installed everything as in the tutorial, everything works correctly, but if I call a Jquery method I get returned an error stating that Jquery was not initialized, that is, it is applying the function before loading Juquery, somebody helps me.

**Comment by v-rudkovskiy** [comment]
Hi @raulti 

jQuery includes only in the admin theme. You need include jquery library in your blade template.

**Comment by raulti** [comment]
Thank you for your help
It's work!
