### ISSUE TITLE
NPM Run Dev error

### ISSUE THREAD

**Issue by rbdiniz** [Labs64/laravel-boilerplate#38]
Hello,

I tried a lot of times install this project following the steps in README.md, but i always get the following error, when I use the command "npm run dev":
 

> vagrant@vagrant-ubuntu-trusty-64:/var/www/html/laravel-boilerplate$ npm run dev
> 
> @ dev /var/www/html/laravel-boilerplate
> npm run development
> 
> 
> @ development /var/www/html/laravel-boilerplate
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/lar
> avel-mix/setup/webpack.config.js
> 
> internal/child_process.js:317
>     throw errnoException(err, 'spawn');
>     ^
> 
> Error: spawn EACCES
>     at exports._errnoException (util.js:1026:11)
>     at ChildProcess.spawn (internal/child_process.js:317:11)
>     at Object.exports.spawn (child_process.js:471:9)
>     at spawn (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/cross-env/node_modules/cross-spawn/index.js:17:18
> )
>     at crossEnv (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/cross-env/dist/index.js:30:38)
>     at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/cross-env/dist/bin/cross-env.js:10:1
> 6)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --
> config=node_modules/laravel-mix/setup/webpack.config.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @ development script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/vagrant/.npm/_logs/2018-02-09T23_11_33_464Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ dev: `npm run development`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @ dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/vagrant/.npm/_logs/2018-02-09T23_11_33_487Z-debug.log

And the debug file:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/home/vagrant/.nvm/versions/node/v8.0.0/bin/node',
> 1 verbose cli   '/home/vagrant/.nvm/versions/node/v8.0.0/bin/npm',
> 1 verbose cli   'run',
> 1 verbose cli   'development' ]
> 2 info using npm@5.0.0
> 3 info using node@v8.0.0
> 4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
> 5 info lifecycle @~predevelopment: @
> 6 silly lifecycle @~predevelopment: no script for predevelopment, continuing
> 7 info lifecycle @~development: @
> 8 verbose lifecycle @~development: unsafe-perm in lifecycle true
> 9 verbose lifecycle @~development: PATH: /home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/bin/node-gyp-bin:$
> 10 verbose lifecycle @~development: CWD: /var/www/html/laravel-boilerplate
> 11 silly lifecycle @~development: Args: [ '-c',
> 11 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --co$
> 12 silly lifecycle @~development: Returned: code: 1  signal: null
> 13 info lifecycle @~development: Failed to exec development script
> 14 verbose stack Error: @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress -$
> 14 verbose stack Exit status 1
> 14 verbose stack     at EventEmitter.<anonymous> (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/util$
> 14 verbose stack     at emitTwo (events.js:125:13)
> 14 verbose stack     at EventEmitter.emit (events.js:213:7)
> 14 verbose stack     at ChildProcess.<anonymous> (/home/vagrant/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/util$
> 14 verbose stack     at emitTwo (events.js:125:13)
> 14 verbose stack     at ChildProcess.emit (events.js:213:7)
> 14 verbose stack     at maybeClose (internal/child_process.js:887:16)
> 14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
> 15 verbose pkgid @
> 16 verbose cwd /var/www/html/laravel-boilerplate
> 17 verbose Linux 3.13.0-141-generic
> 18 verbose argv "/home/vagrant/.nvm/versions/node/v8.0.0/bin/node" "/home/vagrant/.nvm/versions/node/v8.0.0/bin/npm" "r$
> 19 verbose node v8.0.0
> 20 verbose npm  v5.0.0
> 21 error code ELIFECYCLE
> 22 error errno 1
> 23 error @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules -$
> 23 error Exit status 1
> 24 error Failed at the @ development script.
> 24 error This is probably not a problem with npm. There is likely additional logging output above.
> 25 verbose exit [ 1, true ]

What's going on? I already tried:

- Install cross-env as global
- Install/uninstall/reinstall a lot of node.js versions
- Format the VM and reinstall everything again

Regards,
R.

**Comment by v-rudkovskiy** [comment]
Hi, @rbdiniz

 Did you modify your webpack.mix.js file?

What permissions do you have on the node_modules folder? (Try changed to 775)

**Comment by rbdiniz** [comment]
Hello @v-rudkovskiy ,

Thank you for your reply.

I didn't modify my webpack.mix.js. Should I?

> 
> const {mix} = require('laravel-mix');
> const CleanWebpackPlugin = require('clean-webpack-plugin');
> 
> // paths to clean
> var pathsToClean = [
>     'public/assets/app/js',
>     'public/assets/app/css',
>     'public/assets/admin/js',
>     'public/assets/admin/css',
>     'public/assets/auth/css',
> ];
> 
> // the clean options to use
> var cleanOptions = {};
> 
> mix.webpackConfig({
>     plugins: [
>         new CleanWebpackPlugin(pathsToClean, cleanOptions)
>     ]
> });
> 
> /*
>  |--------------------------------------------------------------------------
>  | Mix Asset Management
>  |--------------------------------------------------------------------------
>  |
>  | Mix provides a clean, fluent API for defining some Webpack build steps
>  | for your Laravel application. By default, we are compiling the Sass
>  | file for the application as well as bundling up all the JS files.
>  |
>  */
> 
> /*
>  |--------------------------------------------------------------------------
>  | Core
>  |--------------------------------------------------------------------------
>  |
>  */
> 
> mix.scripts([
>     'node_modules/jquery/dist/jquery.js',
>     'node_modules/pace-progress/pace.js',
> 
> ], 'public/assets/app/js/app.js').version();
> 
> mix.styles([
>     'node_modules/font-awesome/css/font-awesome.css',
>     'node_modules/pace-progress/themes/blue/pace-theme-minimal.css',
> ], 'public/assets/app/css/app.css').version();
> 
> mix.copy([
>     'node_modules/font-awesome/fonts/',
> ], 'public/assets/app/fonts');
> 
> /*
>  |--------------------------------------------------------------------------
>  | Auth
>  |--------------------------------------------------------------------------
>  |
>  */
> 
> mix.styles('resources/assets/auth/css/login.css', 'public/assets/auth/css/login.css').version();
> mix.styles('resources/assets/auth/css/register.css', 'public/assets/auth/css/register.css').version();
> mix.styles('resources/assets/auth/css/passwords.css', 'public/assets/auth/css/passwords.css').version();
> 
> mix.styles([
>     'node_modules/bootstrap/dist/css/bootstrap.css',
>     'node_modules/gentelella/vendors/animate.css/animate.css',
>     'node_modules/gentelella/build/css/custom.css',
> ], 'public/assets/auth/css/auth.css').version();
> 
> /*
>  |--------------------------------------------------------------------------
>  | Admin
>  |--------------------------------------------------------------------------
>  |
>  */
> 
> mix.scripts([
>     'node_modules/bootstrap/dist/js/bootstrap.js',
>     'node_modules/gentelella/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js',
>     'node_modules/gentelella/build/js/custom.js',
> ], 'public/assets/admin/js/admin.js').version();
> 
> mix.styles([
>     'node_modules/bootstrap/dist/css/bootstrap.css',
>     'node_modules/gentelella/vendors/animate.css/animate.css',
>     'node_modules/gentelella/build/css/custom.css',
> ], 'public/assets/admin/css/admin.css').version();
> 
> 
> mix.copy([
>     'node_modules/gentelella/vendors/bootstrap/dist/fonts',
> ], 'public/assets/admin/fonts');
> 
> 
> mix.scripts([
>     'node_modules/select2/dist/js/select2.full.js',
>     'resources/assets/admin/js/users/edit.js',
> ], 'public/assets/admin/js/users/edit.js').version();
> 
> mix.styles([
>     'node_modules/select2/dist/css/select2.css',
> ], 'public/assets/admin/css/users/edit.css').version();
> 
> mix.scripts([
>     'node_modules/gentelella/vendors/Flot/jquery.flot.js',
>     'node_modules/gentelella/vendors/Flot/jquery.flot.time.js',
>     'node_modules/gentelella/vendors/Flot/jquery.flot.pie.js',
>     'node_modules/gentelella/vendors/Flot/jquery.flot.stack.js',
>     'node_modules/gentelella/vendors/Flot/jquery.flot.resize.js',
> 
>     'node_modules/gentelella/vendors/flot.orderbars/js/jquery.flot.orderBars.js',
>     'node_modules/gentelella/vendors/DateJS/build/date.js',
>     'node_modules/gentelella/vendors/flot.curvedlines/curvedLines.js',
>     'node_modules/gentelella/vendors/flot-spline/js/jquery.flot.spline.min.js',
> 
>     'node_modules/gentelella/production/js/moment/moment.min.js',
>     'node_modules/gentelella/vendors/bootstrap-daterangepicker/daterangepicker.js',
> 
> 
>     'node_modules/gentelella/vendors/Chart.js/dist/Chart.js',
>     'node_modules/jcarousel/dist/jquery.jcarousel.min.js',
> 
>     'resources/assets/admin/js/dashboard.js',
> ], 'public/assets/admin/js/dashboard.js').version();
> 
> mix.styles([
>     'node_modules/gentelella/vendors/bootstrap-daterangepicker/daterangepicker.css',
>     'resources/assets/admin/css/dashboard.css',
> ], 'public/assets/admin/css/dashboard.css').version();
> 
> 
> /*
>  |--------------------------------------------------------------------------
>  | Frontend
>  |--------------------------------------------------------------------------
>  |
>  */
> 

The permissions for node_modules folder is 775.

**Comment by v-rudkovskiy** [comment]
Let's try to completely clear the cache before "npm install" command execute

```
rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install
```

Sometimes helps

**Comment by rbdiniz** [comment]
Didn't work. Same error.

Error: spawn  @EACCES
