### ISSUE TITLE
Stylesheets should be loaded in HEAD

### ISSUE THREAD

**Issue by webstractions** [Labs64/laravel-boilerplate#4]
I am getting a brief view of unstyled content when pages are loaded. This due to the stylesheets being loaded near the end of the BODY tag. 

If you move the following in `views/layouts/app.blade.php` into the head section, all will be right.

```
        {{--Styles--}}
        @yield('styles')

        {{--Common App Styles--}}
        {{ Html::style(mix('assets/app/css/app.css')) }}

```
Another problem in this area is the `laravel-debugbar` which probably should be loaded in the head as well (even the javascript). As it stands now, all of that gets spit out together.

**Comment by v-rudkovskiy** [comment]
Fixed in [Labs64/laravel-boilerplate@aa24b94](https://github.com/Labs64/laravel-boilerplate/commit/aa24b94ca0af0811e1fa263e73ba91bb42f4e8fb)
