### ISSUE TITLE
Validation JS 

### ISSUE THREAD

**Issue by gslongo** [Labs64/laravel-boilerplate#40]
Hi,

I'm trying to use built-in JS form validation library but i'm quite stuck... Do anyone has documentation link?

Thanks !

**Comment by r-brown** [comment]
Hi @gslongo ,
I assume you asking [NetLicensing](https://netlicensing.io) docu.

Please refer to this link https://www.labs64.de/confluence/x/pwCo

**Comment by gslongo** [comment]
Hi,

Thank you for your answer. 

No, i'm talking about validator.js library :

node_modules/gentelella/vendors/validator/validator.js

But it's maybe related to another issue. Because the builtin switchery module is not working also :

![capture du 2018-02-24 15-02-29](https://user-images.githubusercontent.com/5636906/36631199-1ed00cd8-1974-11e8-9120-4a0ee15e5a67.png)

Have a nice week-end !

**Comment by r-brown** [comment]
Oh, I see - sorry for that!
Might be you could reach out the developers of https://github.com/puikinsh/gentelella - theme is being used here
or
https://github.com/chriso/validator.js (I assume, this is the library)

**Comment by r-brown** [comment]
Closing the issue as not-relevant.
Gentelella issue need to be created instead.
