### ISSUE TITLE
OCL rumtime exec failed: exec faild: container_linux.go:296: starting container process caused "no such file or directory": unknown

### ISSUE THREAD

**Issue by limjung0515** [Labs64/laravel-boilerplate#41]
I want to use this library.
There is an existing Rarabel framework, but I didn't know how to insert it into my framework so I received it through a single bond.
The first question is, is it my way of using this library?

After deciding to go ahead, I followed the docker section.

1. git clone https://github.com/Labs64/laravel-boilerplate.git
2. cp .env.example .env (after cd laravel-boilerplate)
3. docker-compose up -d
4. docker exec laravelboilerplate_laravel-env_1 ./dockerfiles/bin/prj-build.sh

But an error occurred in this fourth part. The contents are identical with the title.
"OCL rumtime exec failed: exec faild: container_linux.go:296: starting container process caused "no such file or directory": unknown"

If the docker was normally terminated, it could enter the bash script, or it could be connected directly to the BusLogic, but I am stuck in this situation. Help me figure out what the problem is.

**Comment by r-brown** [comment]
Hi @limjung0515 ,
Could you please provide details for you host system, e.g. operation system, version, etc.
As well as the version of the Docker container.

**Comment by limjung0515** [comment]
You mean this kind of thing?
The operating system is Windows 10
Docker version is 17.12.0-ce

Please tell me if you need anything else.

**Comment by r-brown** [comment]
Exactly, this is exactly what I need.
Docker containers share the same kernel and you can't run completely different OS in containers like in VMs. However, you can run different distros of Linux because they do share the same kernel. The isolation level is not as strong as in VM.

The Docker file in the laravel boilerplate project is based on the Linux CentOS 7 distribution: https://github.com/Labs64/laravel-boilerplate/blob/master/dockerfiles/Dockerfile#L1
... so, obviously, you won't be able to run this on Windows.

----

If you have `nodejs` and `npm` installations on your Windows 10 PC, you could go for non-Docker way as it's described here: https://github.com/Labs64/laravel-boilerplate#installation

**Comment by limjung0515** [comment]
Ah ha, the window was a limit! I didn't even think about it.

But one more question arose. If you exclude just 4 of the questions above,
There is no particular error. You can run it locally if you proceed to item 3.
Item 4 is the error.

I used to make up the environment from the docker with laradock.
Laradock procedure is as follows.


1.git clone https://github.com/Laradock/laradock.git

2.cp env-example .env

3.docker-compose up -d nginx mysql redis beanstalkd


Laradock was also executed locally because it only spoke the docker-compose up command.

I want to get back to it.
Is it okay to proceed with boilerplate only three times and use it locally?
I wonder what the necessity is for number 4!

**Comment by r-brown** [comment]
Step 3 is starting Docker environment only.
Step 4 is needed to execute Node.js packages installation in the new nacked (Docker) environment.
This step is also needed is some significant changes in the package structure have been performed (e.g. adding new dependencies, upgrading dependencies versions, etc.)

See also _Step 4_ commands: https://github.com/Labs64/laravel-boilerplate/blob/master/dockerfiles/bin/prj-build.sh

**Comment by r-brown** [comment]
Closing this issue as fixed.
Resolution: wrong Docker host os was used (e.g. Windows vs. Linux)
