### ISSUE TITLE
Enable plurals in JSON translation

### ISSUE THREAD

**Issue by v-rudkovskiy** [Labs64/laravel-boilerplate#42]
Plurals support in JSON translation needs to be added.

**Comment by r-brown** [comment]
Related Laravel Framework issue: https://github.com/laravel/framework/issues/17836

**Comment by r-brown** [comment]
`__trans_choice()` helper fuction at `app/helpers.php` was introduced in order to support plural translations stored in JSON files.

Please find below function definition and usage scenario.

**laravel-boilerplate/app/helpers.php**
```
if (!function_exists('__trans_choice')) {
    /**
     * Translates the given message based on a count from json key.
     *
     * @param $key
     * @param $number
     * @param array $replace
     * @param null $locale
     * @return string
     */
    function __trans_choice($key, $number, array $replace = [], $locale = null)
    {
        return trans_choice(__($key), $number, $replace, $locale);
    }
}
```

**laravel-boilerplate/resources/lang/en.json**
```
{
  "licenses": “There is one NetLicensing license|There are many NetLicensing licenses”
}
```

**How to Use**
```
echo __trans_choice(‘licenses’, 10);
```

**Comment by JunaidQadirB** [comment]
@r-brown This isn't working with single JSON translation file.
I have `LangB.json` in which I have `LangA` texts as keys and `LangB` texts as values as suggested in the Laravel Documentation.
And you suggested function doesn't seem to work with this structure. Really appreciate you input.

**Comment by r-brown** [comment]
Hi, @JunaidQadirB thanks for feedback here. We'll verify this issue.

**Comment by r-brown** [comment]
Hi @JunaidQadirB may I ask you clarify this, as there are not so many differences between Laravel and Boilerplate version?

**Boilerplate**
```
{
  "licenses": “There is one NetLicensing license|There are many NetLicensing licenses”
}

echo __trans_choice(‘licenses’, 10);
```

**Laravel**
```
'apples' => '{0} There are none|[1,19] There are some|[20,*] There are many',
echo trans_choice('messages.apples', 10);
```

ref: https://laravel.com/docs/7.x/localization#pluralization

---

Would u be able to provide your code snippet?
