### ISSUE TITLE
The Mix manifest does not exist

### ISSUE THREAD

**Issue by ghost** [Labs64/laravel-boilerplate#44]
The Mix manifest does not exist. (View: /var/www/laravel-boilerplate/resources/views/auth/login.blade.php)

cant figure out whats the problem.
try'd 
npm install
npm run dev

anyone with same issue ?

**Comment by v-rudkovskiy** [comment]
@versatilegurung Do you have mix-manifest.json file in public folder?

**Comment by versatilegurung** [comment]
Nope

**Comment by ghost** [comment]
@v-rudkovskiy Thanks anyway. Its working now. Cheers for the shout. 👍
