### ISSUE TITLE
Error: pngquant failed to build, make sure that libpng-dev is installed

### ISSUE THREAD

**Issue by AnowarCST** [Labs64/laravel-boilerplate#48]
npm is not installing. Error: pngquant failed to build, make sure that libpng-dev is installed. But I've installed libpng-devel.

$ npm install

> ℹ compiling from source
>   ✔ pngquant pre-build test passed successfully
>   ✖ **Error: pngquant failed to build, make sure that libpng-dev is installed**
>     at Promise.all.then.arr (/var/www/html/laravel-boilerplate/node_modules/imagemin-pngquant/node_modules/bin-build/node_modules/execa/index.js:231:11)
>     at process.internalTickCallback (internal/process/next_tick.js:77:7)
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
> npm ERR! Exit status 1

as I'm using centos
$ **yum install libpng-devel**

> Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
> Package 2:libpng-devel-1.5.13-7.amzn2.0.2.x86_64 already installed and latest version
> Nothing to do

$ node -v
v11.1.0
$ npm -v
6.4.1

**Comment by Panchojr7** [comment]
I have the same error, please fix it !

**Comment by v-rudkovskiy** [comment]
It can not build the binary from source without a compiler.

So for ubuntu/debian, try: `sudo apt-get install build-essential libpng-dev`
