### ISSUE TITLE
Error run npm run dev

### ISSUE THREAD

**Issue by zendzo** [Labs64/laravel-boilerplate#5]
i am getting this error after follow instructions and run npm run dev
`> @ dev /home/mustofa/Code/laravel-boilerplate
> npm run development

> @ development /home/mustofa/Code/laravel-boilerplate
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

Copying bower_components/font-awesome/fonts/ to /home/mustofa/Code/laravel-boilerplate/public/assets/app/fonts
Copying bower_components/gentelella/vendors/bootstrap/dist/fonts to /home/mustofa/Code/laravel-boilerplate/public/assets/admin/fonts
fs.js:1000
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat 'bower_components/gentelella/vendors/bootstrap/dist/fonts'
    at Error (native)
    at Object.fs.statSync (fs.js:1000:11)
    at Object.statSync (/home/mustofa/Code/laravel-boilerplate/node_modules/graceful-fs/polyfills.js:297:22)
    at Object.copySync (/home/mustofa/Code/laravel-boilerplate/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:86)
    at FileCollection.copyTo (/home/mustofa/Code/laravel-boilerplate/node_modules/laravel-mix/src/FileCollection.js:41:12)
    at src.forEach.file (/home/mustofa/Code/laravel-boilerplate/node_modules/laravel-mix/src/FileCollection.js:28:38)
    at Array.forEach (native)
    at FileCollection.copyTo (/home/mustofa/Code/laravel-boilerplate/node_modules/laravel-mix/src/FileCollection.js:28:17)
    at CopyWebpackPlugin.copy.forEach.copy (/home/mustofa/Code/laravel-boilerplate/node_modules/laravel-mix/src/WebpackPlugins/CopyWebpackPlugin.js:10:57)
    at Array.forEach (native)

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/home/mustofa/.nvm/versions/node/v6.10.2/bin/node" "/home/mustofa/.nvm/versions/node/v6.10.2/bin/npm" "run" "development"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script 'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mustofa/Code/laravel-boilerplate/npm-debug.log

npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/home/mustofa/.nvm/versions/node/v6.10.2/bin/node" "/home/mustofa/.nvm/versions/node/v6.10.2/bin/npm" "run" "dev"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ dev script 'npm run development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mustofa/Code/laravel-boilerplate/npm-debug.log
`

**Comment by v-rudkovskiy** [comment]
Be sure to execute the "bower install" command before "npm run dev"

**Comment by zendzo** [comment]
i am really sure. following the instructions step by step without missing something.

`bower install` and then `npm run dev.`
before that i have some issue, it is cross-env, i installed `npm install cross-env`.
but it's remain the same error appear.

**Comment by v-rudkovskiy** [comment]
Сan you provide a log after running bower install?
Did bower create the bower_components folder after bower install?
Try running “sudo bower install”.

**Comment by zendzo** [comment]
`bower install --allow-root`
here is the result
```
bower gentelella#^1.4.0         cached https://github.com/puikinsh/gentelella.git#1.4.0
bower gentelella#^1.4.0       validate 1.4.0 against https://github.com/puikinsh/gentelella.git#^1.4.0
bower bootstrap#^3.3.7          cached https://github.com/twbs/bootstrap.git#3.3.7
bower bootstrap#^3.3.7        validate 3.3.7 against https://github.com/twbs/bootstrap.git#^3.3.7
bower font-awesome#^4.7.0       cached https://github.com/FortAwesome/Font-Awesome.git#4.7.0
bower font-awesome#^4.7.0     validate 4.7.0 against https://github.com/FortAwesome/Font-Awesome.git#^4.7.0
bower jquery#1.9.1 - 3          cached https://github.com/jquery/jquery-dist.git#3.2.1
bower jquery#1.9.1 - 3        validate 3.2.1 against https://github.com/jquery/jquery-dist.git#1.9.1 - 3
bower gentelella#^1.4.0        install gentelella#1.4.0
bower font-awesome#^4.7.0      install font-awesome#4.7.0
bower bootstrap#^3.3.7         install bootstrap#3.3.7
bower jquery#1.9.1 - 3         install jquery#3.2.1

gentelella#1.4.0 bower_components/gentelella

font-awesome#4.7.0 bower_components/font-awesome

bootstrap#3.3.7 bower_components/bootstrap
└── jquery#3.2.1

jquery#3.2.1 bower_components/jquery
```

**Comment by zendzo** [comment]
i think the problem is here
`Error: ENOENT: no such file or directory, stat 'bower_components/gentelella/vendors/bootstrap/dist/fonts'
at Error (native)`

there is no folder bower_components/gentelella/vendors/`bootstrap/dist/fonts`

so i `mkdir bootstrap/dist/fonts ` folder and re run `npm run dev`

and it's work.
