### ISSUE TITLE
Customize Admin template

### ISSUE THREAD

**Issue by priyankadave30** [Labs64/laravel-boilerplate#50]
Hi, i am working on gentelella template and when i am removing some functionalities it is giving me error, instead of showing the dashboard it shows half loaded site. check the link for error below, 

https://snag.gy/HNdLvn.jpg

please reply as soon as possible.

**Comment by r-brown** [comment]
Hello @priyankadave30 ,

Obviously, it's not possible to troubleshoot your issue based on the not fully dashboard screenshot. A changeset on the base template would be really helpful here.

Please also understand, that we do not offer a free customization service, as this going beyond framework capabilities.

Please contact us via email in the [Labs64 profile](https://github.com/Labs64) and we'll be happy to support your customization needs.

Best, Labs64 Team

**Comment by priyankadave30** [comment]
hi, i understand i just wanted to remove functionalities which are not
needed, i make some changes it gives me error as you have seen in my
previous screenshot. accordingly what my output has to be is in the below
screenshot.

https://snag.gy/9aYb2U.jpg
