### ISSUE TITLE
Database migration error on running command "php artisan migrate --seed"

### ISSUE THREAD

**Issue by kumarrahul-rkv** [Labs64/laravel-boilerplate#54]
When I am running " php artisan migrate --seed" this command I am getting the following error

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes (SQL: alter table `protection_shop_to
  kens` add unique `pst_unique`(`user_id`, `success_url`, `cancel_url`))

In PDOStatement.php line 119:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes

In PDOStatement.php line 117:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes

![image](https://user-images.githubusercontent.com/19572222/60149195-82ddd780-97f1-11e9-9043-ace63319217a.png)

**Comment by v-rudkovskiy** [comment]
Fixed in [1251a718](https://github.com/Labs64/laravel-boilerplate/commit/1251a718e6fc234dbf6ca79b5ed5bd464744da32)
