### ISSUE TITLE
Could I integrate in an existing laravel project?, can't start over, please

### ISSUE THREAD

**Issue by byron-perez** [Labs64/laravel-boilerplate#56]

**Comment by r-brown** [comment]
Hello @hominini ,
Integration in an existing project is surely dependent on the complexity of this existing project.
Laravel Boilerplate brings all needed layers, which need to be integrated one-by-one then.

Might be the best approach here would be - still use this boilerplate as a foundation and implement/move your business logic on top of it.

Best regards, [R.Brown](https://netlicensing.io)

**Comment by byron-perez** [comment]
so helpful, thanks
