### ISSUE TITLE
How do I implement the different pages? and UI?

### ISSUE THREAD

**Issue by commentatorboy** [Labs64/laravel-boilerplate#57]
I am a bit confused on how to implement the different UI elements and the pages that are shown in the example. 
I can see that in the original template repo, there is a production folder with different examples, but could not find it in this repo.

I tried to for example find the projects.html example, but could not find it.

I have already compiled and installed everything as the guide mentioned.

Thank you in advance.

**Comment by v-rudkovskiy** [comment]
You can take examples from [gentelella ](https://github.com/puikinsh/gentelella) theme and integrate them with[ laravel "blade templates"](https://laravel.com/docs/5.8/blade)

**Comment by commentatorboy** [comment]
Awesome thanks ! Thought that it were already integrated in this repo, but that is ok.
