### ISSUE TITLE
Directory public/ does not exist

### ISSUE THREAD

**Issue by menadio** [Labs64/laravel-boilerplate#6]
During installation $ php -S localhost:8080 -t public/ returns error "Directory public/ does not exist."

Checked the folders and i can see a public folder with an index.php file and other files in it. How do i resolve this?

**Comment by menadio** [comment]
Resolved the issue by running php artisan serve command and i was able to see the welcome page

**Comment by rabilan** [comment]
first you select correct lumen  project folder then  proceed the command
ex:
if you are project folder name  is blog   you run before folder compiler cannot fetch the correct path so you first ls (list ) command to list the all folder to view the if folder is visible then procced the commad
