### ISSUE TITLE
Upgrade to Laravel 6

### ISSUE THREAD

**Issue by rainerkent** [Labs64/laravel-boilerplate#63]
Laravel 6 has been released for a while... 

Any plans on upgrade???

**Comment by r-brown** [comment]
Hi @rainerkent absolutely - this boilerplate need to be updated to [Laravel 6](https://laravel.com/docs/6.x/releases).
Do you want to take it over?!

**Comment by rainerkent** [comment]
@r-brown I will start working on this. 
I'm unfamiliar with some of the dependencies so I will be needing assistance when I encounter problems about those.
