### ISSUE TITLE
I facing this error please help me.

### ISSUE THREAD

**Issue by RVP04** [Labs64/laravel-boilerplate#70]
![image](https://user-images.githubusercontent.com/8185511/68099767-bd612a80-fedd-11e9-8a6c-2664a818a853.png)
In the membership area i am getting this error. I dont know to debug can u please help me.

**Comment by v-rudkovskiy** [comment]
Fixed in [dd4b37a7b2f4bb4cf36abf6b3b9aa7a70c5bd3f1](https://github.com/Labs64/laravel-boilerplate/commit/dd4b37a7b2f4bb4cf36abf6b3b9aa7a70c5bd3f1)
