### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by rabol** [Labs64/laravel-boilerplate#77]
Any plans for Laravel 7

**Comment by r-brown** [comment]
Laravel 7 - https://laravel.com/docs/7.x/

**Comment by rabol** [comment]
Sorry, my question was more on when or if you are going to upgrade to Laravel 7

**Comment by r-brown** [comment]
Hi @rabol got it :)
We'll verify preconditions here and update Laravel
Thank you for this hint.

**Comment by r-brown** [comment]
Boilerplate upgraded to Laravel7 - https://github.com/Labs64/laravel-boilerplate/commit/37db51e580f15ddaa1c272ff395889d0c6475960
