### ISSUE TITLE
Different configuration for Docker - Need Help 

### ISSUE THREAD

**Issue by ClaudioRojasA** [Labs64/laravel-boilerplate#83]
Hello, i'm doing a project at a class and they required i use this template to work with laravel and Docker, but also told me i have to use Debian Buster and apache, so i wanted to know how i would go about modifying the dockerfile and dockercompose to match what im being asked to do or if i should install without docker and create my own dockerfile but a simpler versión to run the code.
I would appreciate any help because my teachers haven't really taught us how to use docker but we need to use it.

**Comment by r-brown** [comment]
Hello @ClaudeTheRed 

_this is the place where you can change OS (e.g. Debian Buster) for Docker_
https://github.com/Labs64/laravel-boilerplate/blob/master/dockerfiles/Dockerfile#L1

_this is the place where you can change HTTP server (e.g. Apache)_
https://github.com/Labs64/laravel-boilerplate/blob/master/docker-compose.yml#L26

Hope this helps.

**Comment by ClaudioRojasA** [comment]
> Hello @ClaudeTheRed
> 
> _this is the place where you can change OS (e.g. Debian Buster) for Docker_
> https://github.com/Labs64/laravel-boilerplate/blob/master/dockerfiles/Dockerfile#L1
> 
> _this is the place where you can change HTTP server (e.g. Apache)_
> https://github.com/Labs64/laravel-boilerplate/blob/master/docker-compose.yml#L26
> 
> Hope this helps.

Hello, i'm trying to do what you said, but i wonder if what im doing it's alright, cause it's something i haven't used before so a lot of things i just have never heard of.

This is how i modified the dockerfile:
FROM debian:buster

# Install some must-haves
RUN apt-get install -y vim wget sendmail
RUN apt-get install -y git
RUN git --version

# Install PHP 7.2 on Buster
RUN apt-get install -y php7.3
RUN php -v

RUN apt-get install -y \
    php \
    php-bcmath \
    php-cli \
    php-common \
    php-curl \
    php-fpm \
    php-gd \
    php-ldap \
    php-intl \
    php-mbstring \
    php-mysqlnd \
    php-opcache \
    php-pdo \
    php-pear \
    php-pecl-apcu \
    php-pgsql \
    php-process \
    php-recode \
    php-soap \
    php-xml \
    php-zip

#RUN apt-get install -y php-imap php-mcrypt php-pecl-imagick php-pspell php-tidy

# Prepare PHP environment
COPY config/php/php-fpm.conf /etc/php-fpm.conf
COPY config/php/www.conf /etc/php-fpm.d/www.conf
COPY config/php/php.ini /usr/local/etc/php/php.ini
COPY config/php/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/bin/composer
RUN composer --version

# Install Node.js
RUN apt-get install -y nodejs
RUN node -v

# Final update and clean up
#RUN yum -y update
#RUN yum clean all

# Define work directory
WORKDIR /var/www/laravel-boilerplate

# Expose ports
EXPOSE 9000

CMD ["php-fpm", "-F", "-O"]

This is how i modified the docker-compose.yml
version: '3'
services:
  mysql:
    image: mysql:5
    volumes:
      - "./data/db:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    #command: --default_authentication_plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel_boilerplate
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
  laravel-env:
    build: ./dockerfiles
    depends_on:
      - mysql
    volumes:
      - ".:/var/www/laravel-boilerplate"
      - "./dockerfiles/config/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./dockerfiles/config/php/www.conf:/etc/php-fpm.d/www.conf"
      - "./dockerfiles/config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./dockerfiles/config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
  Apache:
    image: httpd:latest
    depends_on:
      - laravel-env
    volumes:
      - ".:/var/www/laravel-boilerplate"
      - "./dockerfiles/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    restart: always


But there's a thing called volume that leads to a nginx config and i don't know what to do with it.

**Comment by r-brown** [comment]
Yes, this might be correct configuration.
You would need to test it locally, however, by starting docker compose.

**Comment by ClaudioRojasA** [comment]
I'm getting errors at 
RUN apt-get install -y php-process

RUN apt-get install -y php-imap php-mcrypt php-pecl-imagick php-pspell php-tidy

and 

RUN mv composer.phar /usr/bin/composer

**Comment by ClaudioRojasA** [comment]
E: Package 'php-mcrypt' has no installation candidate
E: Unable to locate package php-pecl-imagick

mv: cannot stat 'composer.phar': No such file or directory

E: Unable to locate package php-process
